name: aws-greengrass-lite
base: core22
version: '2.2.2'
summary: AWS IoT Greengrass runtime for constrained devices
description: |
  AWS IoT Greengrass nucleus lite provides a lightweight alternative to the
  Greengrass nucleus runtime. The nucleus lite aims to be compatible with the
  Greengrass nucleus, but implements a subset of its functionality for
  constrained devices.

grade: stable
confinement: strict

architectures:
  - amd64
  - arm64

apps:
  ggconfigd:
    command: usr/bin/ggconfigd
    daemon: simple
    plugs:
      - network
      - network-bind
      - hardware-observe
      - system-observe
      - mount-observe
      - process-control
      - log-observe
  iotcored:
    command: usr/bin/iotcored
    plugs:
      - network
      - network-bind
  ggl-cli:
    command: usr/bin/ggl-cli

parts:
  aws-greengrass-lite:
    plugin: dump
    source: .
